### ISSUE TITLE
3장 도커 이미지 만들기

### ISSUE THREAD

**Issue by joyerimi** [psychology50/docker-study#1]

**Comment by TG-Lim** [comment]
논리적 용량과 물리적 용량의 상관관계에 대해 알려주세요.

**Comment by joyerimi** [comment]
논리적 용량은 모든 레이어가 디스크에서 있다는 걸 가정했을 때의 용량입니다.
반면 물리적 용량은 캐시의 레이어를 재사용하고 물리적으로 디스크에 저장되는 용량을 의미합니다.
즉, 논리적 용량과 물리적 용량의 차가 재사용되고 있는 레이어의 용량이라고 보셔도 됩니다.
